
services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: AZpassword
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10