version: "3"
services:
  app:
    build: venv
    links:
      - db

  db:
    image: mysql:8.0
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: AZpassword
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro