
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: AZpassword
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro